### ISSUE TITLE
err converting to HF

### ISSUE THREAD

**Issue by JMHAVANCE** [young-geng/EasyLM#23]
**Command:**
```
python -m EasyLM.models.llama.convert_easylm_to_hf \
    --load_checkpoint='params::/home/nap/Downloads/githubs/EasyLM/easylm_checkpoint/koala_13b.diff.weights' \
    --tokenizer_path='/home/nap/Documents/text-generation-webui/models/llama_original/13B/tokenizer.model' \
    --model_size='13b' \
    --output_dir='/home/nap/Downloads/githubs/EasyLM/easylm_checkpoint/koala-13B-HF'
```

**Output:**
```
Traceback (most recent call last):
  File "/home/nap/miniconda3/envs/EasyLM/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nap/miniconda3/envs/EasyLM/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nap/Downloads/githubs/EasyLM/EasyLM/models/llama/convert_easylm_to_hf.py", line 32, in <module>
    from transformers import LlamaConfig, LlamaForCausalLM
ImportError: cannot import name 'LlamaConfig' from 'transformers' (/home/nap/miniconda3/envs/EasyLM/lib/python3.8/site-packages/transformers/__init__.py)
```

**Do I not have the right version of Transformers?** I used these commands from the docs to set up conda:
```
conda env create -f scripts/gpu_environment.yml
conda activate EasyLM
```

(EasyLM) nap@wintermute:~/Downloads/githubs/EasyLM$ **pip freeze | grep transform**
**transformers==4.27.2**
(Ubuntu 22)

**Comment by young-geng** [comment]
For converting to Huggingface you might need the nightly version of the transformers library that has the LLaMA implementation.

**Comment by JMHAVANCE** [comment]
Thanks, that did the trick!

```pip install git+https://github.com/huggingface/transformers```

(EasyLM) nap@wintermute:~/Downloads/githubs/EasyLM/scripts$ **pip freeze | grep transformers**
transformers @ git+https://github.com/huggingface/transformers@3f96e0b4e483c4c7d4ec9dcdc24b0b0cdf31ea5c
